version: "3.0"
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  logstash_data:
    driver: local
 
networks:
  elastic_network:
    driver: bridge
 
services:
  flask:
    container_name: flask-ws
    stdin_open: true
    tty: true
    build: .
    ports:
      - "6001:5000"
    restart: always
    volumes:
      - .:/flask
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - elastic_network
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=linda123
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic_network

  kibana:
    container_name: kibana
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.7.1
    labels:
      co.elastic.logs/module: kibana
    volumes:
      - kibana_data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic_network

  logstash:
    container_name: logstash
    depends_on:
      - elasticsearch
      - kibana
    image: docker.elastic.co/logstash/logstash:8.7.1
    labels:
      co.elastic.logs/module: logstash
    user: root
    volumes:
      - logstash_data:/usr/share/logstash/data
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./uploads/:/usr/share/logstash/ingest_data/
    networks:
      - elastic_network
