version: "3"
services:
  flask:
    container_name: flask-ws
    stdin_open: true
    tty: true
    build: .
    ports:
      - "6001:5000"
    restart: always
    volumes:
      - .:/flask
    depends_on:
      - elasticsearch
      - logstash
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.enrollment.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.0
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./uploads:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch-data:
  elasticsearch-logs: